package ynu.sxp.demo.common.exception;

public enum ExceptionType {
    VALIDATION_ERROR,
    LOGIN_ERROR,
    LOGIN_CAPTCHA_ERROR,
    BUSINESS_ERROR,
    PERSISTENCE_ERROR,
    DATA_ACCESS_ERROR,
    ASSERT_ERROR,
    ACCESS_DENIED_ERROR,
    NO_RESOURCE_FOUND_ERROR,
    HTTP_MESSAGE_ERROR,
    AUTHENTICATION_ERROR,
    INTERNAL_ERROR
}
